<a href="https://colab.research.google.com/github/saeeRB/project/blob/main/income_prediction_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [ ]:
ic = pd.read_csv('adult.csv')

In [ ]:
ic.head(10)

age         workclass  fnlwgt     education  educational-num  \
0   25           Private  226802          11th                7   
1   38           Private   89814       HS-grad                9   
2   28         Local-gov  336951    Assoc-acdm               12   
3   44           Private  160323  Some-college               10   
4   18                 ?  103497  Some-college               10   
5   34           Private  198693          10th                6   
6   29                 ?  227026       HS-grad                9   
7   63  Self-emp-not-inc  104626   Prof-school               15   
8   24           Private  369667  Some-college               10   
9   55           Private  104996       7th-8th                4   

       marital-status         occupation   relationship   race  gender  \
0       Never-married  Machine-op-inspct      Own-child  Black    Male   
1  Married-civ-spouse    Farming-fishing        Husband  White    Male   
2  Married-civ-spouse    Protective-serv        Husband  White    Male   
3  Married-civ-spouse  Machine-op-inspct        Husband  Black    Male   
4       Never-married                  ?      Own-child  White  Female   
5       Never-married      Other-service  Not-in-family  White    Male   
6       Never-married                  ?      Unmarried  Black    Male   
7  Married-civ-spouse     Prof-specialty        Husband  White    Male   
8       Never-married      Other-service      Unmarried  White  Female   
9  Married-civ-spouse       Craft-repair        Husband  White    Male   

   capital-gain  capital-loss  hours-per-week native-country income  
0             0             0              40  United-States  <=50K  
1             0             0              50  United-States  <=50K  
2             0             0              40  United-States   >50K  
3          7688             0              40  United-States   >50K  
4             0             0              30  United-States  <=50K  
5             0             0              30  United-States  <=50K  
6             0             0              40  United-States  <=50K  
7          3103             0              32  United-States   >50K  
8             0             0              40  United-States  <=50K  
9             0             0              10  United-States  <=50K

In [ ]:
ic.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [ ]:
ic.shape

(48842, 15)

In [ ]:
import numpy as np
ic = ic.replace({'?' :np.nan})

In [ ]:
ic =ic.dropna()

In [ ]:
ic = ic.drop

In [ ]:
ic.income.replace({'<=50k':0 , '>=50k':1} , inplace= True)

In [ ]:
ic.education.value_counts()

HS-grad         15784
Some-college    10878
Bachelors        8025
Masters          2657
Assoc-voc        2061
11th             1812
Assoc-acdm       1601
10th             1389
7th-8th           955
Prof-school       834
9th               756
12th              657
Doctorate         594
5th-6th           509
1st-4th           247
Preschool          83
Name: education, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
le = LabelEncoder()

In [ ]:
ic[ic.select_dtypes(include='object').columns] = ic[ic.select_dtypes(include='object').columns].apply(le.fit_transform)

In [ ]:
from sklearn.model_selection import train_test_split
ic_train , ic_test = train_test_split(ic,test_size= .2)

In [ ]:
ic_train_x = ic_train.iloc[:,0:-1]
ic_train_y = ic_train.iloc[:,-1]
ic_test_x = ic_test.iloc[:,0:-1]
ic_test_y = ic_test.iloc[:,-1]

In [ ]:
from sklearn.linear_model import  LogisticRegression
rc = LogisticRegression()
rc.fit(ic_train_x , ic_train_y)
pred_rc= rc.predict(ic_test_x)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

In [ ]:
confusion_matrix(ic_test_y , pred_rc)

array([[7062,  367],
       [1699,  641]])

In [ ]:
print(classification_report(ic_test_y , pred_rc))

              precision    recall  f1-score   support

           0       0.81      0.95      0.87      7429
           1       0.64      0.27      0.38      2340

    accuracy                           0.79      9769
   macro avg       0.72      0.61      0.63      9769
weighted avg       0.77      0.79      0.76      9769



In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(ic_train_x , ic_train_y)
pred_dt = dt.predict(ic_test_x)

In [ ]:
confusion_matrix(ic_test_y, pred_dt)

array([[6509,  920],
       [ 905, 1435]])

In [ ]:
print(classification_report(ic_test_y , pred_dt))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88      7429
           1       0.61      0.61      0.61      2340

    accuracy                           0.81      9769
   macro avg       0.74      0.74      0.74      9769
weighted avg       0.81      0.81      0.81      9769



In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(ic_train_x, ic_train_y)
pred_rfc = rfc.predict(ic_test_x)

In [ ]:
confusion_matrix(ic_test_y , pred_rfc)

array([[6965,  464],
       [ 872, 1468]])

In [ ]:
print(classification_report(ic_test_y , pred_rfc))

              precision    recall  f1-score   support

           0       0.89      0.94      0.91      7429
           1       0.76      0.63      0.69      2340

    accuracy                           0.86      9769
   macro avg       0.82      0.78      0.80      9769
weighted avg       0.86      0.86      0.86      9769



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier( n_neighbors= 50)
knn.fit(ic_train_x, ic_train_y)
pred_knn = knn.predict(ic_test_x)

In [ ]:
confusion_matrix(ic_test_y , pred_knn)

array([[7390,   39],
       [1946,  394]])

In [ ]:
print(classification_report(ic_test_y , pred_knn))

              precision    recall  f1-score   support

           0       0.79      0.99      0.88      7429
           1       0.91      0.17      0.28      2340

    accuracy                           0.80      9769
   macro avg       0.85      0.58      0.58      9769
weighted avg       0.82      0.80      0.74      9769

